### ISSUE TITLE
Exchanged portrait

### ISSUE THREAD

**Issue by redovic** [Playful-Interactive-Environments/pie.fh-hagenberg.at#30]
Thehleitner  file ""daniel-rammer.jpg" has been changed.
Not visible on live website yet.

**Comment by redovic** [comment]
@hochleitner

**Comment by hochleitner** [comment]
Everything worked (see http://playful-interactive-environments.github.io/pie.fh-hagenberg.at/people/), but I currently have to manually update pie.fh-hagenberg.at since it's not hosted on GitHub yet.
Will push the files to the server after I've updated a few other things. And maybe we can finally get that domain @diephuis? 😸
